# Generated by Django 3.2.2 on 2021-05-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210524_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image',
            field=models.ImageField(default='logo.png', upload_to='profile_pics'),
        ),
    ]
