# Generated by Django 3.2.2 on 2021-05-27 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
